export let letterPositions = [
    { letter: "П", position: 1, description: "Description for П in position 1" },
    { letter: "П", position: 2, description: "Description for П in position 2" },
    { letter: "П", position: 3, description: "Description for П in position 3" },
    { letter: "П", position: 4, description: "Description for П in position 4" },
    { letter: "Н", position: 1, description: "Description for Н in position 1" },
    { letter: "Н", position: 2, description: "Description for Н in position 2" },
    { letter: "Н", position: 3, description: "Description for Н in position 3" },
    { letter: "Н", position: 4, description: "Description for Н in position 4" },
    { letter: "Б", position: 1, description: "Description for Б in position 1" },
    { letter: "Б", position: 2, description: "Description for Б in position 2" },
    { letter: "Б", position: 3, description: "Description for Б in position 3" },
    { letter: "Б", position: 4, description: "Description for Б in position 4" },
    { letter: "В", position: 1, description: "Description for В in position 1" },
    { letter: "В", position: 2, description: "Description for В in position 2" },
    { letter: "В", position: 3, description: "Description for В in position 3" },
    { letter: "В", position: 4, description: "Description for В in position 4" }
  ];

 export let typenames = [
    "ПНБВ",
    "ПНВБ",
    "ПВНБ",
    "ПВБН",
    "ПБВН",
    "ПБНВ",
    "НПБВ",
    "НПВБ",
    "НВПБ",
    "НВБП",
    "НБПВ",
    "НБВП",
    "БПНВ",
    "БПВН",
    "БВНП",
    "БВПН",
    "БНВП",
    "БНПВ",
    "ВПНБ",
    "ВПБН",
    "ВНПБ",
    "ВНБП",
    "ВБПН",
    "ВБНП"
  ];